---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[loggly::default]
    attributes:
      loggly:
        token: test
        severity: notice
        port: 514
        files_to_monitor:
          -
            name: test
            tag: test-log
            path: /path/to/test-log.log
